Parameters:
  ServiceName:
    Description: Name for ECR repo
    Type: String
  ProjectPhase:
    Description: Phase of the project
    Type: String

Resources:
  ImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ServiceName
      ImageTagMutability: IMMUTABLE
      RepositoryPolicyText:
        Version: "2008-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
      Tags:
        - Key: Project
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref ProjectPhase
