Parameters:
  ServiceName:
    Description: Name for ECR repo
    Type: String
  ProjectPhase:
    Description: Phase of the project
    Type: String

Resources:
  # ECR Repo (BE)
  ImageRepo:
    Type: AWS::ECR::Repository
    Properties:
      RepositoryName: !Ref ServiceName
      ImageTagMutability: IMMUTABLE
      RepositoryPolicyText:
        Version: "2012-10-17"
        Statement:
          - Sid: AllowPushPull
            Effect: Allow
            Principal:
              AWS:
                - "*"
            Action:
              - "ecr:GetDownloadUrlForLayer"
              - "ecr:BatchGetImage"
              - "ecr:BatchCheckLayerAvailability"
              - "ecr:PutImage"
              - "ecr:InitiateLayerUpload"
              - "ecr:UploadLayerPart"
              - "ecr:CompleteLayerUpload"
      Tags:
        - Key: Project
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref ProjectPhase

  # S3 Bucket (FE)
  FeBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub "fe.${ServiceName}.samour.net"
      Tags:
        - Key: Project
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref ProjectPhase

  # IAM for Github Actions
  GithubActionUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ServiceName}GithubUser"
      Tags:
        - Key: Project
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref ProjectPhase

  GithubActionPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: !Sub "${ServiceName}GithubPolicy"
      Users:
        - !Ref GithubActionUser
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: GetAuthorizationTokenStatement
            Effect: Allow
            Action:
              - "ecr:GetAuthorizationToken"
            Resource: "*"
          - Sid: S3Upload
            Effect: Allow
            Action:
              - "s3:PutObject"
            Resource: !Sub "arn:aws:s3:::fe.${ServiceName}.samour.net/*"
          - Sid: ManageCFStack
            Effect: Allow
            Action:
              - "cloudformation:DescribeStacks"
              - "cloudformation:CreateChangeSet"
              - "cloudformation:DescribeChangeSet"
              - "cloudformation:ExecuteChangeSet"
            Resource: !Sub "arn:aws:cloudformation:*:${AWS::AccountId}:stack/${ServiceName}-app/*"
          - Sid: ManageAppResources
            Effect: Allow
            Action:
              - "ec2:*"
              - "acm:*"
              - "elasticloadbalancing:*"
              - "route53:*"
              - "dynamodb:*"
              - "cloudwatch:*"
              - "ecs:*"
              - "iam:*"
              - "s3:*"
              - "cloudfront:*"
            Resource: "*"

Outputs:
  Repository:
    Description: URI of image repository
    Value: !GetAtt ImageRepo.RepositoryUri
    Export:
      Name: !Sub "${ServiceName}-ecr-uri"
