Parameters:
  ServiceName:
    Description: Name for github repo
    Type: String
  ProjectPhase:
    Description: Phase of the project
    Type: String

Resources:
  GithubActionUser:
    Type: AWS::IAM::User
    Properties:
      UserName: !Sub "${ServiceName}GithubUser"
      Tags:
        - Key: Project
          Value: !Ref ServiceName
        - Key: Phase
          Value: !Ref ProjectPhase
