server:
  servlet:
    context-path: /${SERVICE_NAME}

dynamodb:
  tables:
    user:
      tableName: ${SERVICE_NAME}-user
      canonicalUsernameIndex: ${SERVICE_NAME}-user-canonical-username
    session:
      tableName: ${SERVICE_NAME}-session
    link-definition:
      table-name: ${SERVICE_NAME}-link-definition
      label-index: ${SERVICE_NAME}-link-definition-label

web:
  cors:
    allowedOrigins:
      - 'http://localhost:3000'
      - 'https://${FE_DNS_NAME}'

cache:
  sessions:
    ttl: PT3M
