server:
  servlet:
    context-path: /${SERVICE_NAME}

dynamodb:
  tables:
    user:
      tableName: ${SERVICE_NAME}-user
      canonicalUsernameIndex: ${SERVICE_NAME}-user-canonical-username
    session:
      tableName: ${SERVICE_NAME}-session

web:
  cors:
    allowedOrigins:
      - 'http://localhost:3000'
      - 'https://${FE_DNS_NAME}'
