server:
  servlet:
    context-path: /${SERVICE_NAME}

dynamodb:
  tables:
    user:
      tableName: ${SERVICE_NAME}-user
      canonicalUsernameIndex: ${SERVICE_NAME}-user-canonical-username
    session:
      tableName: ${SERVICE_NAME}-session
