name: Deploy App

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      target_environment:
        required: true
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true

env:
  AWS_REGION: ap-southeast-2

jobs:
  create_plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Create Cloudformation Plan
        env:
          VERSION: ${{ inputs.version }}
        run: ./create-service.sh
        working-directory: build
      - name: Wait for plan
        env:
          VERSION: ${{ inputs.version }}
        run: ./wait-service-change-set.sh
        working-directory: build
      - name: Review Cloudformation Plan
        env:
          VERSION: ${{ inputs.version }}
        run: ./describe-service-change-set.sh
        working-directory: build

  execute_plan:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.target_environment }}
    needs:
      - create_plan
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Execute Plan
        env:
          VERSION: ${{ inputs.version }}
        run: ./execute-service-change-set.sh
        working-directory: build
      - name: Wait for deploy completion
        env:
          VERSION: ${{ inputs.version }}
        run: ./wait-service-stack-update.sh
        working-directory: build
